# Generated by Django 5.0.1 on 2024-02-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='book_audio/%Y/%m/%d/', verbose_name='Kitobning audio shakli'),
        ),
        migrations.AddField(
            model_name='book',
            name='download_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Yuklab olishlar soni'),
        ),
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='book_file/%Y/%m/%d/', verbose_name='kitobning PDF varianti'),
        ),
    ]
